server:
  port: 8082
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true



mybatis:
  type-aliases-package: top.codekiller.security.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    top.codekiller.security: debug

