
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


manager:
  jwt:
    secret: ea61b46dse2@manager@9ds966@codekiller@33da # 登录校验的密钥
    pubKeyPath: E:\chrome\token\\rsa.pub # 公钥地址
    priKeyPath: E:\chrome\token\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    headerName: Authorization  #token的名称

mybatis:
  type-aliases-package: top.codekiller.test.springsecurity.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    top.codekiller.test.springsecurity: debug
